import { Merriweather } from 'next/font/google';
import '../styles/globals.css';
import { AuthProvider, Navbar } from '@/components';
import { ReactNode } from 'react';
import cn from 'classnames';

// TODO: move font to fonts.ts, pick global default & move MW to heading only
// https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// TODO: font picker
const merriweather = Merriweather({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className={cn(merriweather.className, 'light')}>
      <AuthProvider>
        <body>
          <main className='min-h-screen flex flex-col items-center bg-light-primary dark:bg-dark-primary transition-colors duration-300'>
            <Navbar />
            <div className={'pageContainer'}>{children}</div>
          </main>
        </body>
      </AuthProvider>
    </html>
  );
}
