import { Merriweather } from 'next/font/google';
import '../styles/globals.css';
import { Navbar } from '@/components';

// TODO: move font to fonts.ts, pick global default & move MW to heading only
// https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// TODO: font picker
const merriweather = Merriweather({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={merriweather.className}>
      <body>
        <main className='min-h-screen flex flex-col items-center'>
          <Navbar />
          <div className={'pageContainer'}>{children}</div>
        </main>
      </body>
    </html>
  );
}
